version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - .env:/app/.env
    depends_on:
      - postgres
    networks:
      - donor_network

  postgres:
    image: postgres:15-alpine 
    container_name: etl_postgres_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=Clinic
      - POSTGRES_USER=postgres
      - POSTGRES_DB=donor_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - donor_network

networks:
  donor_network:
    driver: bridge

volumes:
  postgres_data: